# https://github.com/aschmelyun/docker-compose-laravel
version: '3'

networks:
  public:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - public

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ~/data/mysql/${DB_DATABASE}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - public

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/app
    ports:
      - "9000:9000"
    networks:
      - public

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - php
    networks:
      - public

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/app
    depends_on:
      - mysql
    working_dir: /var/www/app
    entrypoint: ['php', '/var/www/app/artisan']
    networks:
      - public
